
import "../globals.css";
import Sidebar from "@/components/admin/Siderbar";
import Header from "@/components/admin/Header";
import { ToastContainer } from "react-toastify";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={` antialiased`}
      >
        <div className=" flex  ">
          <ToastContainer
            position="top-center"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
          <div className=" h-screen">
            <Sidebar />
          </div>
          <div className=" flex-1 ">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
